services:
  rag-service:
    build:
      context: ..
      dockerfile: service.Dockerfile
    image: proveo/tutoring/service
    volumes:
      - ../reading:/opt/docs:ro
    networks: ["backend"]
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:?err}
      - ANTHROPIC_MODEL_NAME=claude-sonnet-4-20250514
      - LANGSMITH_TRACING=true
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT:?err}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY:?err}
      - VECTOR_DIR=/app/vector_store
      - DOCS_URL=/opt/docs
    restart: unless-stopped

  api:
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    image: proveo/tutoring/api
    volumes:
      - ../reading:/opt/docs:ro
    networks: ["backend", "frontend"]
    environment:
      - RAG_SERVICE_URL=http://service:8800
      - DOCS_URL=/opt/docs
    ports:
      - "3000:3000"
    depends_on:
      - rag-service
    restart: unless-stopped

  web:
    build:
      context: ..
      dockerfile: docker/web.Dockerfile
    image: proveo/tutoring/web
    networks: ["frontend"]
    ports:
      - "8080:80"
    depends_on:
      - api
    restart: unless-stopped

networks:
  frontend:
  backend:
